export { default as BackNextButtons} from "../components/BackNextButtons";
export { default as ScreenDarkcomponent} from "../components/ScreenDarkcomponent";
export { default as SidebarDetailfilling} from "../components/SidebarDetailfilling";
export { default as Education } from "../components/Educationpage";
export { default as Header } from "../components/Header";
export { default as Headingsection } from "../components/Headingsection";
export { default as Input } from "../components/Input";
export { default as Keyskills } from "../components/Keyskillspage";
export { default as Navbar } from "../components/Navbar";
export { default as PersonalInformation } from "../components/PersonalInformationpage";
export { default as ResumePreview } from "../components/ResumePreview";
export { default as Selectcomponent } from "../components/Selectcomponent";
export { default as TemplateEducation } from "../components/TemplateEducation";
export { default as TemplateKeyskill } from "../components/TemplateKeyskill";
export { default as ExperienceSection } from "../components/Experiencepage";
export { default as Workexperience } from "../components/Workexperience";